-- Pack 4/5: Rotasi Gambar (6 soal)

DO $$
DECLARE pk uuid;
BEGIN
  INSERT INTO question_packs (exam_type, subject, title, description, question_count, is_free, is_published)
  VALUES ('CPNS', 'TIU', 'Rotasi Gambar', 'Soal figural: hasil rotasi gambar (90°, 180°, 270°)', 6, true, true)
  RETURNING id INTO pk;

  INSERT INTO questions (pack_id, exam_type, subject, subtopic, question_type, difficulty, question_text, question_image_url, options, correct_option, explanation_text) VALUES (
    pk, 'CPNS', 'TIU', 'Figural', 'MULTIPLE_CHOICE', 'SEDANG',
    'Gambar berikut diputar 90° searah jarum jam. Hasilnya adalah ...',
    'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxMjAgODAiIHN0cm9rZT0iIzFhMWExYSIgc3Ryb2tlLXdpZHRoPSIyLjUiIGZpbGw9Im5vbmUiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCI+PHBhdGggZD0iTTYwLDY0IEw2MCwxNiBNNTIsMjQgTDYwLDE2IEw2OCwyNCIvPjwvc3ZnPg==',
    '[{"id":"A","text":"A","imageUrl":"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxMjAgODAiIHN0cm9rZT0iIzFhMWExYSIgc3Ryb2tlLXdpZHRoPSIyLjUiIGZpbGw9Im5vbmUiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCI+PHBhdGggZD0iTTM2LDQwIEw4NCw0MCBNNzYsMzIgTDg0LDQwIEw3Niw0OCIvPjwvc3ZnPg=="},{"id":"B","text":"B","imageUrl":"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxMjAgODAiIHN0cm9rZT0iIzFhMWExYSIgc3Ryb2tlLXdpZHRoPSIyLjUiIGZpbGw9Im5vbmUiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCI+PHBhdGggZD0iTTYwLDE2IEw2MCw2NCBNNTIsNTYgTDYwLDY0IEw2OCw1NiIvPjwvc3ZnPg=="},{"id":"C","text":"C","imageUrl":"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxMjAgODAiIHN0cm9rZT0iIzFhMWExYSIgc3Ryb2tlLXdpZHRoPSIyLjUiIGZpbGw9Im5vbmUiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCI+PHBhdGggZD0iTTg0LDQwIEwzNiw0MCBNNDQsMzIgTDM2LDQwIEw0NCw0OCIvPjwvc3ZnPg=="},{"id":"D","text":"D","imageUrl":"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxMjAgODAiIHN0cm9rZT0iIzFhMWExYSIgc3Ryb2tlLXdpZHRoPSIyLjUiIGZpbGw9Im5vbmUiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCI+PHBhdGggZD0iTTYwLDY0IEw2MCwxNiBNNTIsMjQgTDYwLDE2IEw2OCwyNCIvPjwvc3ZnPg=="},{"id":"E","text":"E","imageUrl":"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxMjAgODAiIHN0cm9rZT0iIzFhMWExYSIgc3Ryb2tlLXdpZHRoPSIyLjUiIGZpbGw9Im5vbmUiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCI+PHBvbHlnb24gcG9pbnRzPSI4MCw0MCA0MCwyMCA0MCw2MCIvPjwvc3ZnPg=="}]'::jsonb,
    'A',
    'Rotasi 90° CW: panah ke atas → panah ke kanan. Jawaban: A.'
  );
  INSERT INTO questions (pack_id, exam_type, subject, subtopic, question_type, difficulty, question_text, question_image_url, options, correct_option, explanation_text) VALUES (
    pk, 'CPNS', 'TIU', 'Figural', 'MULTIPLE_CHOICE', 'SEDANG',
    'Gambar berikut diputar 180°. Hasilnya adalah ...',
    'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxMjAgODAiIHN0cm9rZT0iIzFhMWExYSIgc3Ryb2tlLXdpZHRoPSIyLjUiIGZpbGw9Im5vbmUiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCI+PHBvbHlnb24gcG9pbnRzPSI2MCwxOCAzOCw2MiA4Miw2MiIvPjwvc3ZnPg==',
    '[{"id":"A","text":"A","imageUrl":"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxMjAgODAiIHN0cm9rZT0iIzFhMWExYSIgc3Ryb2tlLXdpZHRoPSIyLjUiIGZpbGw9Im5vbmUiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCI+PHBvbHlnb24gcG9pbnRzPSIzOCw0MCA4MiwxOCA4Miw2MiIvPjwvc3ZnPg=="},{"id":"B","text":"B","imageUrl":"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxMjAgODAiIHN0cm9rZT0iIzFhMWExYSIgc3Ryb2tlLXdpZHRoPSIyLjUiIGZpbGw9Im5vbmUiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCI+PHBvbHlnb24gcG9pbnRzPSI4Miw0MCAzOCwxOCAzOCw2MiIvPjwvc3ZnPg=="},{"id":"C","text":"C","imageUrl":"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxMjAgODAiIHN0cm9rZT0iIzFhMWExYSIgc3Ryb2tlLXdpZHRoPSIyLjUiIGZpbGw9Im5vbmUiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCI+PHBvbHlnb24gcG9pbnRzPSI2MCw2MiAzOCwxOCA4MiwxOCIvPjwvc3ZnPg=="},{"id":"D","text":"D","imageUrl":"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxMjAgODAiIHN0cm9rZT0iIzFhMWExYSIgc3Ryb2tlLXdpZHRoPSIyLjUiIGZpbGw9Im5vbmUiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCI+PHBvbHlnb24gcG9pbnRzPSI2MCwxOCAzOCw2MiA4Miw2MiIvPjwvc3ZnPg=="},{"id":"E","text":"E","imageUrl":"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxMjAgODAiIHN0cm9rZT0iIzFhMWExYSIgc3Ryb2tlLXdpZHRoPSIyLjUiIGZpbGw9Im5vbmUiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCI+PHBvbHlnb24gcG9pbnRzPSI2MCwyMCA4MCw0MCA2MCw2MCA0MCw0MCIvPjwvc3ZnPg=="}]'::jsonb,
    'C',
    'Rotasi 180°: segitiga ke atas → ke bawah (terbalik penuh). Jawaban: C.'
  );
  INSERT INTO questions (pack_id, exam_type, subject, subtopic, question_type, difficulty, question_text, question_image_url, options, correct_option, explanation_text) VALUES (
    pk, 'CPNS', 'TIU', 'Figural', 'MULTIPLE_CHOICE', 'SEDANG',
    'Gambar berikut diputar 90° berlawanan jarum jam. Hasilnya adalah ...',
    'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxMjAgODAiIHN0cm9rZT0iIzFhMWExYSIgc3Ryb2tlLXdpZHRoPSIyLjUiIGZpbGw9Im5vbmUiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCI+PHBvbHlsaW5lIHBvaW50cz0iMzgsNjIgMzgsMTggODIsMTgiLz48L3N2Zz4=',
    '[{"id":"A","text":"A","imageUrl":"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxMjAgODAiIHN0cm9rZT0iIzFhMWExYSIgc3Ryb2tlLXdpZHRoPSIyLjUiIGZpbGw9Im5vbmUiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCI+PHBvbHlsaW5lIHBvaW50cz0iMzgsNjIgMzgsMTggODIsMTgiLz48L3N2Zz4="},{"id":"B","text":"B","imageUrl":"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxMjAgODAiIHN0cm9rZT0iIzFhMWExYSIgc3Ryb2tlLXdpZHRoPSIyLjUiIGZpbGw9Im5vbmUiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCI+PHBvbHlsaW5lIHBvaW50cz0iODIsNjIgODIsMTggMzgsMTgiLz48L3N2Zz4="},{"id":"C","text":"C","imageUrl":"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxMjAgODAiIHN0cm9rZT0iIzFhMWExYSIgc3Ryb2tlLXdpZHRoPSIyLjUiIGZpbGw9Im5vbmUiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCI+PHBvbHlsaW5lIHBvaW50cz0iMzgsMTggMzgsNjIgODIsNjIiLz48L3N2Zz4="},{"id":"D","text":"D","imageUrl":"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxMjAgODAiIHN0cm9rZT0iIzFhMWExYSIgc3Ryb2tlLXdpZHRoPSIyLjUiIGZpbGw9Im5vbmUiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCI+PHBvbHlsaW5lIHBvaW50cz0iODIsMTggODIsNjIgMzgsNjIiLz48L3N2Zz4="},{"id":"E","text":"E","imageUrl":"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxMjAgODAiIHN0cm9rZT0iIzFhMWExYSIgc3Ryb2tlLXdpZHRoPSIyLjUiIGZpbGw9Im5vbmUiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCI+PHBvbHlnb24gcG9pbnRzPSI0MCw0MCA4MCwyMCA4MCw2MCIvPjwvc3ZnPg=="}]'::jsonb,
    'C',
    'Rotasi 90° CCW: L-shape NE (sudut di kanan-atas) → SE (sudut di kanan-bawah). Jawaban: C.'
  );
  INSERT INTO questions (pack_id, exam_type, subject, subtopic, question_type, difficulty, question_text, question_image_url, options, correct_option, explanation_text) VALUES (
    pk, 'CPNS', 'TIU', 'Figural', 'MULTIPLE_CHOICE', 'SEDANG',
    'Gambar berikut diputar 90° searah jarum jam. Hasilnya adalah ...',
    'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxMjAgODAiIHN0cm9rZT0iIzFhMWExYSIgc3Ryb2tlLXdpZHRoPSIyLjUiIGZpbGw9Im5vbmUiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCI+PHBvbHlsaW5lIHBvaW50cz0iODIsNjIgODIsMTggMzgsMTgiLz48L3N2Zz4=',
    '[{"id":"A","text":"A","imageUrl":"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxMjAgODAiIHN0cm9rZT0iIzFhMWExYSIgc3Ryb2tlLXdpZHRoPSIyLjUiIGZpbGw9Im5vbmUiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCI+PHBvbHlsaW5lIHBvaW50cz0iMzgsNjIgMzgsMTggODIsMTgiLz48L3N2Zz4="},{"id":"B","text":"B","imageUrl":"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxMjAgODAiIHN0cm9rZT0iIzFhMWExYSIgc3Ryb2tlLXdpZHRoPSIyLjUiIGZpbGw9Im5vbmUiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCI+PHBvbHlsaW5lIHBvaW50cz0iODIsNjIgODIsMTggMzgsMTgiLz48L3N2Zz4="},{"id":"C","text":"C","imageUrl":"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxMjAgODAiIHN0cm9rZT0iIzFhMWExYSIgc3Ryb2tlLXdpZHRoPSIyLjUiIGZpbGw9Im5vbmUiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCI+PHBvbHlsaW5lIHBvaW50cz0iMzgsMTggMzgsNjIgODIsNjIiLz48L3N2Zz4="},{"id":"D","text":"D","imageUrl":"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxMjAgODAiIHN0cm9rZT0iIzFhMWExYSIgc3Ryb2tlLXdpZHRoPSIyLjUiIGZpbGw9Im5vbmUiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCI+PHBvbHlsaW5lIHBvaW50cz0iODIsMTggODIsNjIgMzgsNjIiLz48L3N2Zz4="},{"id":"E","text":"E","imageUrl":"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxMjAgODAiIHN0cm9rZT0iIzFhMWExYSIgc3Ryb2tlLXdpZHRoPSIyLjUiIGZpbGw9Im5vbmUiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCI+PHBvbHlnb24gcG9pbnRzPSI2MCwyMiA3OCw0MCA2MCw1OCA0Miw0MCIvPjwvc3ZnPg=="}]'::jsonb,
    'A',
    'Rotasi 90° CW: L-shape NW (sudut di kiri-atas) → NE (sudut di kanan-atas). Jawaban: A.'
  );
  INSERT INTO questions (pack_id, exam_type, subject, subtopic, question_type, difficulty, question_text, question_image_url, options, correct_option, explanation_text) VALUES (
    pk, 'CPNS', 'TIU', 'Figural', 'MULTIPLE_CHOICE', 'SEDANG',
    'Gambar berikut diputar 270° searah jarum jam (= 90° CCW). Hasilnya adalah ...',
    'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxMjAgODAiIHN0cm9rZT0iIzFhMWExYSIgc3Ryb2tlLXdpZHRoPSIyLjUiIGZpbGw9Im5vbmUiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCI+PHBhdGggZD0iTTYwLDY0IEw2MCwxNiBNNTIsMjQgTDYwLDE2IEw2OCwyNCIvPjwvc3ZnPg==',
    '[{"id":"A","text":"A","imageUrl":"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxMjAgODAiIHN0cm9rZT0iIzFhMWExYSIgc3Ryb2tlLXdpZHRoPSIyLjUiIGZpbGw9Im5vbmUiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCI+PHBhdGggZD0iTTM2LDQwIEw4NCw0MCBNNzYsMzIgTDg0LDQwIEw3Niw0OCIvPjwvc3ZnPg=="},{"id":"B","text":"B","imageUrl":"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxMjAgODAiIHN0cm9rZT0iIzFhMWExYSIgc3Ryb2tlLXdpZHRoPSIyLjUiIGZpbGw9Im5vbmUiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCI+PHBhdGggZD0iTTYwLDE2IEw2MCw2NCBNNTIsNTYgTDYwLDY0IEw2OCw1NiIvPjwvc3ZnPg=="},{"id":"C","text":"C","imageUrl":"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxMjAgODAiIHN0cm9rZT0iIzFhMWExYSIgc3Ryb2tlLXdpZHRoPSIyLjUiIGZpbGw9Im5vbmUiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCI+PHBhdGggZD0iTTg0LDQwIEwzNiw0MCBNNDQsMzIgTDM2LDQwIEw0NCw0OCIvPjwvc3ZnPg=="},{"id":"D","text":"D","imageUrl":"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxMjAgODAiIHN0cm9rZT0iIzFhMWExYSIgc3Ryb2tlLXdpZHRoPSIyLjUiIGZpbGw9Im5vbmUiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCI+PHBhdGggZD0iTTYwLDY0IEw2MCwxNiBNNTIsMjQgTDYwLDE2IEw2OCwyNCIvPjwvc3ZnPg=="},{"id":"E","text":"E","imageUrl":"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxMjAgODAiIHN0cm9rZT0iIzFhMWExYSIgc3Ryb2tlLXdpZHRoPSIyLjUiIGZpbGw9Im5vbmUiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCI+PHJlY3QgeD0iNDIiIHk9IjIyIiB3aWR0aD0iMzYiIGhlaWdodD0iMzYiLz48L3N2Zz4="}]'::jsonb,
    'C',
    'Rotasi 270° CW sama dengan 90° CCW. Panah ke atas → ke kiri. Jawaban: C.'
  );
  INSERT INTO questions (pack_id, exam_type, subject, subtopic, question_type, difficulty, question_text, question_image_url, options, correct_option, explanation_text) VALUES (
    pk, 'CPNS', 'TIU', 'Figural', 'MULTIPLE_CHOICE', 'SEDANG',
    'Gambar berikut diputar 180°. Hasilnya adalah ...',
    'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxMjAgODAiIHN0cm9rZT0iIzFhMWExYSIgc3Ryb2tlLXdpZHRoPSIyLjUiIGZpbGw9Im5vbmUiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCI+PHBhdGggZD0iTTM2LDQwIEw4NCw0MCBNNzYsMzIgTDg0LDQwIEw3Niw0OCIvPjwvc3ZnPg==',
    '[{"id":"A","text":"A","imageUrl":"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxMjAgODAiIHN0cm9rZT0iIzFhMWExYSIgc3Ryb2tlLXdpZHRoPSIyLjUiIGZpbGw9Im5vbmUiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCI+PHBhdGggZD0iTTYwLDY0IEw2MCwxNiBNNTIsMjQgTDYwLDE2IEw2OCwyNCIvPjwvc3ZnPg=="},{"id":"B","text":"B","imageUrl":"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxMjAgODAiIHN0cm9rZT0iIzFhMWExYSIgc3Ryb2tlLXdpZHRoPSIyLjUiIGZpbGw9Im5vbmUiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCI+PHBhdGggZD0iTTYwLDE2IEw2MCw2NCBNNTIsNTYgTDYwLDY0IEw2OCw1NiIvPjwvc3ZnPg=="},{"id":"C","text":"C","imageUrl":"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxMjAgODAiIHN0cm9rZT0iIzFhMWExYSIgc3Ryb2tlLXdpZHRoPSIyLjUiIGZpbGw9Im5vbmUiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCI+PHBhdGggZD0iTTg0LDQwIEwzNiw0MCBNNDQsMzIgTDM2LDQwIEw0NCw0OCIvPjwvc3ZnPg=="},{"id":"D","text":"D","imageUrl":"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxMjAgODAiIHN0cm9rZT0iIzFhMWExYSIgc3Ryb2tlLXdpZHRoPSIyLjUiIGZpbGw9Im5vbmUiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCI+PHBhdGggZD0iTTM2LDQwIEw4NCw0MCBNNzYsMzIgTDg0LDQwIEw3Niw0OCIvPjwvc3ZnPg=="},{"id":"E","text":"E","imageUrl":"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxMjAgODAiIHN0cm9rZT0iIzFhMWExYSIgc3Ryb2tlLXdpZHRoPSIyLjUiIGZpbGw9Im5vbmUiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCI+PGNpcmNsZSBjeD0iNjAiIGN5PSI0MCIgcj0iMTgiLz48bGluZSB4MT0iNDcuNCIgeTE9IjQwIiB4Mj0iNzIuNiIgeTI9IjQwIi8+PGxpbmUgeDE9IjYwIiB5MT0iMjcuNCIgeDI9IjYwIiB5Mj0iNTIuNiIvPjwvc3ZnPg=="}]'::jsonb,
    'C',
    'Rotasi 180°: panah ke kanan → ke kiri (arah terbalik). Jawaban: C.'
  );
END $$;